#!/usr/bin/perl

use warnings;
my $base="v4"; # This is the base version, either v3 or v4 atm.
my @tags = `git tag -l`;
my $version = "$base.0";
foreach (reverse(@tags)) {
	if (m/$base.*/) {
		s/\n//g;
		$version = $_;
		last;
	}
}
my @tmp;
@tmp = split(/$base\./, $version);
$tmp[1] = int($tmp[1]) + 1;
my $new_version = "$base.$tmp[1]";
print "Last tag is $version. Proposed new tag is $new_version. Proceed? (y/n): ";
my $answer = <STDIN>;
if ($answer =~ '(y|Y)') {
	print("OK, continuing\n");
} else {
	print("Aborting\n");
	exit(1);
}
sleep(1); # give user a moment to panic CTRL-C if needs be
# Write version into file for setup.py
die("Could not write version\n") unless (0 == system("echo $new_version > version"));
# Create the git tag
die("Could not create git tag\n") unless (0 == system("git tag -a $new_version -m \"Auto-Release Version $new_version\""));
# Now run the code to push to pip
die("Could not build and deploy to pypi\n") unless (0 == system("python ./setup.py sdist bdist_wheel && twine upload --repository-url https://test.pypi.org/legacy/ dist/*"));
