#!/usr/bin/env perl
chdir("./flac2all_pkg");
$run=0;
while($run != 22000) {
	print "Run $run\n";
	# Every 250 runs, delete the testout to reconvert
	system("rm","-rf","../testoutput") if (($run % 250) == 0);
	die("Failed on run $run\n") if system(
		"python3",
		"./__init__.py",
		"vorbis",
		"-c",
		"-n", "m",
		"-o", "../testoutput/",
		"../testinput/"
	);
	sleep(0.8);
	$run++;
}
