test::
	python ./__main__.py mp3 --lame-options '-preset standard' -o /storage/flac2mp3 /mnt/Muzika/Lossless/

debug:
	python -m pdb ./__main__.py mp3 --lame-options '-preset standard' -o /storage/flac2mp3 /mnt/Muzika/Lossless/
